name: flutter

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }} using ${{ matrix.channel }} channel
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        channel: [stable, beta]
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: "Setup Flutter"
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}
          cache: true

      - run: dart --version
      - run: flutter --version

      - name: "Execute `pub get`"
        run: flutter pub get

      - name: "Show `doctor` output"
        run: flutter doctor -v

      - name: "Check code formatting issues"
        run: dart format --set-exit-if-changed .

      - name: "Show `analyze` output"
        run: flutter analyze .

      - name: "Run tests"
        run: flutter test -r expanded

      - name: "Build AppBundle"
        run: flutter build appbundle
        working-directory: ./example
        continue-on-error: true

      - name: "Build iOS"
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: flutter build ios --release --no-codesign
        working-directory: ./example
        continue-on-error: true
