# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "22 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 180
          days-before-close: 30
          exempt-all-pr-milestones: true
          stale-issue-message: "This issue has stalled."
          stale-pr-message: "This pull request has stalled."
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          close-issue-message: "This issue has been closed due to inactivity."
          close-pr-message: "This pull request has been closed due to inactivity."
          ascending: true
